#testbuild

before_script: 
  - python --version
  - sudo apt-get update
  - sudo apt-get install -y pip


stages:
  - build
  - test
  
build:
  image: ubuntu:latest
  stage: build
  script:
    - echo "Building"
    - pip install setuptools
    - python setup.py install


test:
  image: ubuntu:latest
  stage: test
  script:
    - echo "Testing"
    - pip install setuptools
    - python setup.py install
    - python -c 'import acoular'

