#testbuild
stages:
  - build
  - test
  
before_install: 
  - python --version

build:
  image: ubuntu:latest
  stage: build
  script:
    - echo "Building"
    - pip3 install setuptools
    - python setup.py install


test:
  image: ubuntu:latest
  stage: test
  script:
    - echo "Testing"
    - pip3 install setuptools
    - python setup.py install
    - python -c 'import acoular'

