#testbuild

before_script: 
  - python3 --version
  #- python3 -m pip install --user setuptools
  #- sudo apt-get update
  #- sudo apt-get install -y pip


stages:
  - build
  - test
  
build:
  image: ubuntu:latest
  stage: build
  script:
    - echo "Building"
    #- pip install setuptools
    - python3 setup.py install


test:
  image: ubuntu:latest
  stage: test
  script:
    - echo "Testing"
    #- pip install setuptools
    - python3 setup.py install
    - python3 -c 'import acoular'

