#testbuild
stages:
  - build
  - test

build:
  image: python:3.7
  stage: build
  script:
    - echo "Building"
    - pip install -U pip setuptools 
    - python setup.py install


test:
  image: python:3.7
  stage: test
  script:
    - echo "Testing"
    - pip install -U pip setuptools 
    - python setup.py install
    - python -c 'import acoular'

