#testbuild

#image: "python:3.7"

before_script: 
  - python3 --version
  - uname -a
  #- python3 -m pip install --user setuptools
  - sudo apt-get update
  - sudo apt-get install -y python3-pip


stages:
  - build
  - test
  
build:
  stage: build
  script:
    - echo "Building"
    - pip3 install setuptools
    - pwd
    #- python3 setup.py install

test:
  stage: test
  script:
    - echo "Testing"
    - pip3 install setuptools
    #- python3 setup.py install
    #- python3 -c 'import acoular'
    

