#testbuild

#image: "python:3.7"

before_script: 
  - python --version
  - uname -a
  #- python3 -m pip install --user setuptools
  - sudo apt-get update
  - sudo apt-get install -y pip


stages:
  - build
  - test
  
build:
  stage: build
  script:
    - echo "Building"
    - pip install setuptools
    - python setup.py install

test:
  stage: test
  script:
    - echo "Testing"
    - pip install setuptools
    - python setup.py install
    - python -c 'import acoular'
    

