language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - chmod +x ./acoular/tests/run_tests.sh
  
install:
  - pip install ".[install_requires]" . # install package + test dependencies
 
script: 

  - ./acoular/tests/run_tests.sh # run tests

#after_success:
 # - codecov # submit coverage
  
  
  
