language: python

python:
  #- 2.7
  - 3.5
  - 3.6

before_install:
  # Python PIP install
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
 install:
  - pip install ".acoular" . # install package + test dependencies
  
script: 

  - acoular/tests/run_tests.sh # run tests

after_success:
  - codecov # submit coverage
  
  
  
