language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - chmod +x ./acoular/tests/run_tests.sh
  
install:
  #- pip install . # install package
   - sudo python setup.py install
 
script: 
  # test import
  - python -c 'import acoular'
  # run tests
  - ./acoular/tests/run_tests.sh # run tests

#after_success:
 # - codecov # submit coverage
  
  
  
