language: python

matrix:
  # This will launch a separate build for each Python version you add
  # Feel free to add extra environment variables as needed
  include:
   # - python: 2.7
    - python: 3.5
    - python: 3.6
    # - python: 3.7

before_install:
  # Python PIP install
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
 install:
  - pip install ".acoular" . # install package + test dependencies
  
#script: 

  #- acoular/tests/run_tests.sh # run tests

after_success:
  - codecov # submit coverage
  
  
  
