language: python

#operating sys and python versions
matrix:
  include:
    # Python 2 support will be dropped
    #- name: "Python 2.7 on Xenial Linux"
    #  python: 2.7    
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7          
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11  # Python 3.7 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode9.4  # Python 3.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.6         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
      #Testing Windows
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows 
      before_install:
        #- choco install python  # this install takes at least 1 min 30 sec
        #- python -m pip install --upgrade pip
         - MINICONDA_PATH=/c/tools/miniconda3/;
         - MINICONDA_PATH_WIN=`cygpath --windows $MINICONDA_PATH`;
         - MINICONDA_SUB_PATH=$MINICONDA_PATH/Scripts;
         - choco install openssl.light;
         - choco install miniconda3 --params="'/AddToPath:1 /D:$MINICONDA_PATH_WIN'";
       
      # env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install: 
  - python --version
  - pip install -U pip
  - chmod +x ./acoular/tests/run_tests.sh
  
install:
  # try pip
  #- pip install -e . # install package
  
  # 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
  # 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        python3 setup.py install;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
          export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$PATH";
          # for conda version 4.4 or later
          source $MINICONDA_PATH/etc/profile.d/conda.sh;
          hash -r;
          conda config --set always_yes yes --set changeps1 no;
          conda update -q conda;
          echo "Python $CONDA_PYTHON running on $TRAVIS_OS_NAME";
          conda env create --name test-environment python=3.7 ;
          conda activate test-environment;
          conda install libpython;
          python setup.py install;
    else
        python setup.py install;
    fi
  
 
script: 
  # test import
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       python3 -c 'import acoular';
    else
       python -c 'import acoular';
     fi
  
  # run tests from test dir
  - cd acoular/tests/
    
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       bash run_tests_osx.sh;
    else
       bash run_tests.sh;
     fi
  #- python 'test_beamformer_results.py'

#after_success:
 # - codecov # submit coverage
  
  
  
