language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  
os:
  - linux
  - osx
  #- windows
  
#osx_image: xcode8.3

before_install:
# osx deps
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  
  - python --version
  - pip install -U pip
  - chmod +x ./acoular/tests/run_tests.sh
  
install:
  #- pip install . # install package
  - python setup.py install
 
script: 
  # test import
  - python -c 'import acoular'
  # run tests
  - ./acoular/tests/run_tests.sh # run tests
  - python './acoular/tests/test_beamformer_results.py'

#after_success:
 # - codecov # submit coverage
  
  
  
