package:
  name: acoular
  version: "17.10"

source:
  path: ../../acoular

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - acoular = acoular:main
    #
    # Would create an entry point called acoular that calls acoular.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy >=1.10.2
    - scipy >=0.13
    - scikit-learn >=0.15
    - pytables >=3.1
    - traits >=4.4
    - numba >=0.21
#    - chaco >=4.4
    - libpython [win]

  run:
    - python >=2.7,<3.6
    - pyqt >=4.10,<5.6.0
    - matplotlib >=1.1.1,<1.5.3
    - numpy >=1.10.2
    - numba >=0.21
    - scipy >=0.13
    - scikit-learn >=0.15
    - pytables >=3.1
    - traits >=4.6
    - traitsui >=5.1.0
#    - configparser #just for python version 2.7
#    - chaco >=2.7

test:
  # Python imports
#  imports:
#    - acoular

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.acoular.org
  license: BSD License
  summary: 'Library for acoustic beamforming'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
