package:
  name: acoular
  version: "20.02"

source:
  path: ../../acoular

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - acoular = acoular:main
    #
    # Would create an entry point called acoular that calls acoular.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy >=1.11.3
    - scipy >=1.1.0
    - scikit-learn >=0.19.1
    - pytables >=3.4.4
    - traits >=4.6.0
    - numba >=0.40.0
    - libpython [win]

  run:
    - python >=3.6
    - pyqt >=5.6
    - numpy >=1.11.3
    - numba >=0.40.0
    - scipy >=0.1.0
    - scikit-learn >=0.19.1
    - pytables >=3.4.4
    - traits >=4.6.0

test:
  # Python imports

  files: # from recipe folder
 #   - some file

  source_files: # from acoular folder
    - acoular/tests/
    - examples/

  imports:
    - acoular

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.acoular.org
  license: BSD License
  summary: 'Library for acoustic beamforming'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
